import UIKit

struct StringConstants {
    static let kLblI: String = "i"
    static let k: String = ""
    static let kLbl8992: String = "₹899"
    static let kMsg100Moneyback: String = "100% MoneyBack Guarantee"
    static let kMsgHurryLaunchO: String = "Hurry! Launch offer: 50% Off "
    static let kMsgOrStartWithO: String = "Or start with our trial pack"
    static let kMsg100Available: String = "100% Available & Verified Properties"
    static let kLbl25Properties: String = "25 Properties"
    static let kMsgDedicatedRelat: String = "Dedicated Relationship Manager"
    static let kMsgValidity30Da: String = "Validity: 30 Days"
    static let kLbl1199: String = "1199"
    static let kLblFaqS: String = "FAQ’s"
    static let kLblSaver: String = "SAVER"
    static let kMsgHurryLaunchO2: String = "Hurry! Launch offer: "
    static let kHttpFail: String = "HTTP request failed"
    static let kLbl10Properties: String = "10 Properties"
    static let kMsgValidity10Da: String = "Validity: 10 Days"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kLbl999: String = "₹999"
    static let kLbl50Off: String = "50% Off "
    static let kMsgAvailableAndV: String = "Available and Verified"
    static let kLbl699: String = "699"
    static let kLblIntroducing: String = "Introducing"
    static let kLbl300s: String = "300s"
    static let kLbl899: String = "899"
    static let kLblMoneyback: String = "MONEYBACK"
    static let kMsgPricesInclOf: String = "Prices incl. of GST"
    static let kLbl: String = "₹"
    static let kMsgValidity20Da: String = "Validity: 20 Days"
    static let kLblApplyCoupon: String = "Apply Coupon"
    static let kLblHousingPromise: String = "Housing Promise"
    static let kInvalidUrl: String = "Invalid URL"
    static let kLbl20Properties: String = "20 Properties"
    static let kMsgSubscribeToSa: String = "Subscribe to Saver"
}
